import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/component/Layout";
import ProfilePic from "../../public/images/profile/darkNahid.png";
import Image from 'next/image'
import AnimatedText from "@/component/AnimatedText";




const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=" flex w-full min-h-screen text-dark font-mont">
        <Layout className="pt-0">
        <div className="flex items-center justify-between w-full">
          <div className="w-1/2">
            <Image src={ProfilePic} alt="nahio Hasan" className="w-full h-auto" ></Image>
          </div>
          <div className="w-1/2">
          
          <AnimatedText text="Turning Vision Into Reality With Code And Design." className=" !text-left mb-4"/>
          <p>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
          Explore my latest projects and articles, showcasing my expertise in React.js and web development</p>
          </div>
        </div>
        </Layout>
      </main>
    </>
  );
}
