import React from 'react'
import Head from "next/head";
import Link from 'next/link'
import Image  from 'next/image';
import Layout from "@/component/Layout";
import AnimatedText from "@/component/AnimatedText";
import { GithubIcon } from '@/component/Icons';
import ProjectImg1 from "../../public/images/projects/ChatApp.png"
import ProjectImg2 from "../../public/images/projects/bikerZOne.png"
import ProjectImg3 from "../../public/images/projects/TeaHouse.png"
import ProjectImg4 from "../../public/images/projects/G3.png"
import ProjectImg5 from "../../public/images/projects/creative.png"
import ProjectImg6 from "../../public/images/projects/penguin fahsion.png"



const FeaturedProject = ({type, title, summmary, img, link, github})=>{
  return(
    <article className='w-full flex items-center relative justify-between roounded-br-2xl rounded-3xl border  border-solid bg-light p-12 border-dark shadow-2xl'>
                    <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] roounded-br-3xl rounded-[2.5rem] bg-dark" />

      <Link href={link} target='_blank'
      className='w-1/2 cursor-pointer overflow-hidden rounded-lg'
      >
      <Image src={img} alt={title} className='w-full h-auto'/>
      </Link>
      <div className='w-1/2 flex flex-col items-start justify-between pl-6'>
        <span className='text-primary font-medium text-xl'>{type}</span>
        <Link href={link} target='_blank' className='hover:underline underline-offset-2'>
      <h2 className='my-2 w-full text-left text-4xl font-bold'>{title}</h2>
      </Link>
      <p className='my-2 font-medium text-dark/80'>{summmary}</p>
      <div className='mt-2 flex items-center'>
      <Link href={github} target='_blank' className='w-10'><GithubIcon /></Link>
      <Link href={link} target='_blank'
      className='ml-4 rounded-lg bg-dark text-lg font-semibold text-light p-2 px-6 '>Visit Project</Link>
      </div>
      </div>
    </article>
  )
}
const Project1 =({title,type,img,link,github})=>{

  return(
     <article className='w-full flex flex-col items-center justify-center rounded-2xl border border-solid border-dark bg-light p-6 relative'>
       <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] roounded-br-3xl rounded-[2rem] bg-dark" />
      <Link href={link} target='_blank'
      className='w-full cursor-pointer overflow-hidden rounded-lg'
      >
      <Image src={img} alt={title} className='w-full h-auto'/>
      </Link>
      <div className='w-full flex flex-col items-start justify-between mt-4'>
        <span className='text-primary font-medium text-xl'>{type}</span>
        <Link href={link} target='_blank' className='hover:underline underline-offset-2'>
      <h2 className='my-2 w-full text-left text-3xl font-bold'>{title}</h2>
      </Link>
     
      <div className='w-full mt-2 flex items-center justify-between'>
      <Link href={link} target='_blank'
      className=' text-lg font-semibold  '>Visit </Link>
      <Link href={github} target='_blank' className='w-8'><GithubIcon /></Link>
      
      </div>
      </div>
     </article>
  )
}


const project = () => {
  return (
    <>
    <Head>
        <title>Nahid | Projects Page</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
    <main className="w-full mb-16 flex px-10 flex-col  items-center justify-center">
        <Layout className='pt-16'>
        <AnimatedText text="Imagination Trumps Knowledge!" className="  !text-8xl dark:text-light mb-14"/>
          <div className='grid mt-5 grid-cols-12 gap-24'>
            <div className='col-span-12'>
              <FeaturedProject
          title="Chatting Application "  
          img={ProjectImg1}  
            summmary="  A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
              It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
              local currency."
              link="/"
              github="/"
              type="Featured Project"
              
              />
            </div>
            <div className='col-span-6'>
            <Project1 
            title="Tea House | Tea Shop"  
            img={ProjectImg3}  
             
                link="/"
                github="/"
                type="Featured Project" />
            </div>
            <div className='col-span-6'>
            <Project1 
            title="G3-Architects"  
            img={ProjectImg4}  
             
                link="https://nahidulhasan4.github.io/G3-archtirs/"
                github="/"
                type="Featured Project" />
            </div>
            <div className='col-span-6'>
            </div>
            <div className='col-span-12'>
            <FeaturedProject
          title="Biker Zone "  
          img={ProjectImg2}  
            summmary="  A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
              It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
              local currency."
              link="https://nahidulhasan4.github.io/Bikers_Zone/"
              github="/"
              type="Featured Project"
              
              />
            </div>
            <div className='col-span-6'>
            <Project1 
            title="Creative Service "  
            img={ProjectImg5}  
             
                link="/"
                github="/"
                type="Featured Project" />
            </div>
            <div className='col-span-6'>
            <Project1 
            title=" Penguin Fashion"  
            img={ProjectImg6}  
             
                link="/"
                github="/"
                type="Featured Project" />
            </div>
            <div className='col-span-6'>
            </div>
          </div>

        </Layout>
    </main>

    </>
  )
}

export default project