import React from 'react'
import Head from "next/head";
import Link from 'next/link'
import Image  from 'next/image';
import Layout from "@/component/Layout";
import AnimatedText from "@/component/AnimatedText";
import { GithubIcon } from '@/component/Icons';
import Project1 from "../../public/images/projects/crypto-screener-cover-image.jpg"



const FeaturedProject = ({type, title, summmary, img, link, github})=>{
  return(
    <article className='w-full flex items-center justify-between mt-5 rounded-3xl border border-solid bg-light border-dark shadow-2xl'>
      <Link href={link} target='_blank'
      className='w-1/2 cursor-pointer overflow-hidden rounded-lg'
      >
      <Image src={img} alt={title} className='w-full h-auto'/>
      </Link>
      <div className='w-1/2 flex flex-col items-start justify-between pl-6'>
        <span className='text-primary font-medium text-xl'>{type}</span>
        <Link href={link} target='_blank'>
      <h2>{title}</h2>
      </Link>
      <p>{summmary}</p>
      <div>
      <Link href={github} target='_blank'><GithubIcon /></Link>
      <Link href={link} target='_blank'>Visit PRoject</Link>
      </div>
      </div>
    </article>
  )
}




const project = () => {
  return (
    <>
    <Head>
        <title>Nahid | Projects Page</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
    <main className="w-full mb-16 flex flex-col mx-5 items-center justify-center">
        <Layout className='pt-16'>
            <AnimatedText  text="Imagination trump Knowledge" />
          <div className='grid  grid-cols-12 gap-24'>
            <div className='col-span-12'>
              <FeaturedProject
          title="Biker Zone "  
          img={Project1}  
            summmary="  A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
              It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
              local currency."
              link="/"
              github="/"
              type="Featured Project"
              
              />
            </div>
            <div className='col-span-6'>
            Project-1
            </div>
            <div className='col-span-6'>
            Project-2
            </div>
            <div className='col-span-12'>
              Future Project 
            </div>
            <div className='col-span-6'>
            Project-1
            </div>
            <div className='col-span-6'>
            Project-2
            </div>
          </div>

        </Layout>
    </main>

    </>
  )
}

export default project