import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Layout from "@/component/Layout";
import AnimatedText from "@/component/AnimatedText";
import { GithubIcon } from "@/component/Icons";
import ProjectImg1 from "../../public/images/projects/ChatApp.png";
import ProjectImg2 from "../../public/images/projects/bikerZOne.png";
import ProjectImg3 from "../../public/images/projects/TeaHouse.png";
import ProjectImg4 from "../../public/images/projects/G3.png";
import ProjectImg5 from "../../public/images/projects/creative.png";
import ProjectImg6 from "../../public/images/projects/penguin fahsion.png";
import Homeg01 from "../../public/images/projects/homeg01.png";
import { motion } from "framer-motion";
// this page need to work daily here need improvement on project 

const FremerImage = motion(Image);

const FeaturedProject = ({ type, title, summmary, img, link, github }) => {
  return (
    <article className="w-full flex items-center relative justify-between roounded-br-2xl rounded-3xl border  border-solid bg-light p-12 border-dark shadow-2xl">
      <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] roounded-br-3xl rounded-[2.5rem] bg-dark" />

      <Link
        href={link}
        target="_blank"
        className="w-1/2 cursor-pointer overflow-hidden rounded-lg"
      >
        <FremerImage
          src={img}
          alt={title}
          className="w-full h-auto"
          whileHover={{ scale: 1.2 }}
          transition={{ duration: 0.2 }}
        />
      </Link>
      <div className="w-1/2 flex flex-col items-start justify-between pl-6">
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link href={link} target="_blank" className="">
          <h2 className="my-2 w-full relative text-left text-4xl font-bold group">
            {title}
            <span
              className={`h-[1px] inline-block  bg-dark absolute left-0 bottom-0.5 group-hover:w-full transition-[width] ease duration-1000 dark:bg-light`}
            >
              &nbsp;
            </span>
          </h2>
        </Link>
        <p className="my-2 font-medium text-dark/80">{summmary}</p>
        <div className="mt-2 flex items-center">
          <Link href={github} target="_blank" className="w-10">
            <GithubIcon />
          </Link>
          <Link
            href={link}
            target="_blank"
            className="ml-4 rounded-lg bg-dark text-lg font-semibold text-light p-2 px-6 "
          >
            Visit Project
          </Link>
        </div>
      </div>
    </article>
  );
};
const Project1 = ({ title, type, img, link, github }) => {
  return (
    <article className="w-full flex flex-col items-center justify-center rounded-2xl border border-solid border-dark bg-light p-6 relative">
      <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] roounded-br-3xl rounded-[2rem] bg-dark" />
      <Link
        href={link}
        target="_blank"
        className="w-full cursor-pointer overflow-hidden rounded-lg"
      >
        <FremerImage
          src={img}
          alt={title}
          className="w-full h-auto max-h-[270px]"
          whileHover={{ scale: 1.2 }}
          transition={{ duration: 0.2 }}
        />
      </Link>
      <div className="w-full flex flex-col items-start justify-between mt-4">
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link href={link} target="_blank" className="">
          <h2 className="my-2 w-full text-left relative text-3xl font-bold group">
            {title}
            <span
              className={`h-[1px] inline-block  bg-dark absolute left-0 bottom-0.5 group-hover:w-full transition-[width] ease duration-300 dark:bg-light`}
            >
              &nbsp;
            </span>
          </h2>
        </Link>

        <div className="w-full mt-2 flex items-center justify-between">
          <Link
            href={link}
            target="_blank"
            className=" text-lg font-semibold  "
          >
            Visit{" "}
          </Link>
          <Link href={github} target="_blank" className="w-8">
            <GithubIcon />
          </Link>
        </div>
      </div>
    </article>
  );
};

const project = () => {
  return (
    <>
      <Head>
        <title>Nahid | Projects Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full mb-16 flex px-10 flex-col  items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText
            text="Imagination Trumps Knowledge!"
            className="  !text-8xl dark:text-light mb-14"
          />
          <div className="grid mt-5 grid-cols-12 gap-24">
            <div className="col-span-12">
              <FeaturedProject
                title="Chatting Application "
                img={ProjectImg1}
                summmary="  A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
              It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
              local currency."
                link="/"
                github="/"
                type="Featured Project"
              />
            </div>
            <div className="col-span-6">
              <Project1
                title="Tea House | Tea Shop"
                img={ProjectImg3}
                link="/"
                github="/"
                type="Done  Project"
              />
            </div>
            <div className="col-span-6">
              <Project1
                title="Homeg 01 | Architecture"
                img={Homeg01}
                link="https://nahidulhasan4.github.io/Homge-bootstrap/"
                github="/"
                type="Complete Project"
              />
            </div>
            <div className="col-span-6"></div>
            <div className="col-span-12">
              <FeaturedProject
                title="Axtro | Game Seller "
                img={ProjectImg2}
                summmary="  A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
              It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
              local currency."
                link="https://axtro.vercel.app/"
                github="/"
                type="Featured Project"
              />
            </div>
            <div className="col-span-6">
              <Project1
                title="Creative Service "
                img={ProjectImg5}
                link="/"
                github="/"
                type="Featured Project"
              />
            </div>
            <div className="col-span-6">
              <Project1
                title=" Penguin Fashion"
                img={ProjectImg6}
                link="/"
                github="/"
                type="Featured Project"
              />
            </div>
            <div className="col-span-6"></div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default project;
